version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      # sync vendor
      - git submodule sync
      - git submodule update --init
      - /usr/local/bin/dynamodb-local &
      - bundle install
      - env
      # - bundle exec rspec
      - bash -eux .codebuild/integration.sh

artifacts:
  files:
    - README.md
    # - target/javawebdemo.war